name = "MixedHalfLife"
uuid = "a2ed6a5e-96a6-440e-bd2e-f64b57a6e44e"
version = "0.1.0"
authors = ["Dan Sprague <dsprague@broadinstitute.org>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
CairoMakie = "0.15.7"
Distributions = "0.25.122"
HypothesisTests = "0.11.6"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.12.0"
MCMCChains = "7.6.0"
NNlib = "0.9.31"
Optim = "1.13.3"
PrettyTables = "3.1.2"
Statistics = "1.11.1"
Turing = "0.41.4"
